//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Admin_Tbl
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        [DisplayName("Role")]
        public string Password { get; set; }
        public string user_ID { get; set; }
    }
}
