//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Car_Tbl
    {
        public int id { get; set; }
        public string WIN_Number { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Type_Body { get; set; }
        public string Class { get; set; }
        public int Year_Release { get; set; }
        public int Mileage { get; set; }
        public string Color { get; set; }
        public string Type_Transmission { get; set; }
        public string Type_Drive { get; set; }
        public int Power { get; set; }
        public int Price_Per_Day { get; set; }
        public string Contition { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public Car_Tbl()
        {
            Image = "../Image/defaulst.jpeg";
        }
    }
}
