//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public string FIO_Customer { get; set; }
        public string FIO_Manager { get; set; }
        public string Car_Brand { get; set; }
        public string Car_Model { get; set; }
        public string Car_WIN_Number { get; set; }
        public string Additional_Options { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.DateTime Date_End { get; set; }
        public double Price { get; set; }
        public string Condition { get; set; }
        public string Notes { get; set; }
        public string id_client { get; set; }

        public Contract() { }

        public Contract(string FIO_Customer, string FIO_Manager, string Car_Brand, string Car_Model, string Car_WIN_Number, string Additional_Options,
                         DateTime Date_Start, DateTime Date_End, double Price, string Condition, string Notes, string id_client)
        {
            this.FIO_Customer = FIO_Customer;
            this.FIO_Manager = FIO_Manager;
            this.Car_Brand = Car_Brand;
            this.Car_Model = Car_Model;
            this.Car_WIN_Number = Car_WIN_Number;
            this.Additional_Options = Additional_Options;
            this.Date_Start = Date_Start;
            this.Date_End = Date_End;
            this.Price = Price;
            this.Condition = Condition;
            this.Notes = Notes;
            this.id_client = id_client;
        } 
    }
}
