//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Tbl
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Passport_Data { get; set; }
        public string Drivers_License { get; set; }
        public string Address { get; set; }
    }
}
