//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Tbl
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Passport_Data { get; set; }
        public string Drivers_License { get; set; }
        public string Address { get; set; }
        public string Login { get; set; }
        public string user_ID { get; set; }
        public string Phone { get; set; }

        public Customer_Tbl (string FIO, DateTime BirthDate, string Passport_Data, string Drivers_License,  string Address,
                             string Login, string user_ID, string Phone)
        {
            this.FIO = FIO;
            this.BirthDate = BirthDate;
            this.Passport_Data = Passport_Data;
            this.Drivers_License = Drivers_License;
            this.Address = Address;
            this.Login = Login;
            this.user_ID = user_ID;
            this.Phone = Phone;
        }

        public Customer_Tbl ()
        {

        }
    }
}
